version: '3'
services:
  strapi:
    image: strapi-service
    build: .
    ports:
      - '3005:3005'
    environment:
      - NODE_ENV=production
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - strapi
    restart: always
